version: "3.3"
services:
  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'crm'   
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_HOST: 'localhost'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  # webapp:
  #   build: .
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
